[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
tokio = { version = "1.43.0", features = ["full"] }  # âœ… Make sure "full" is enabled
dotenv = "0.15.0"
jsonwebtoken = "9.3.1"
serde = "1.0.218"
serde_json = "1.0.140"
sqlx = "0.8.3"
